import enum

class FileDownloadStatus(enum.Enum):
    NOT_DOWNLOADED = 0
    DOWNLOADED_FROM_ACCEPTED_WEBSITE = 1
    DOWNLOADED_FROM_PDF = 2
    POSSIBLY_SPURIOUS = 3

class ErrorCode(enum.Enum):
    OK = 0
    ERROR_CONNECTING_TO_SERVER = 1
    ERROR_SEARCH_RETURNED_NOTHING = 2
    ERROR_RETRIEVING_BUTTON_LINK = 3
    ERROR_OPENING_BUTTON_LINK = 4
    ERROR_DOWNLOADING_LINK = 5
    ERROR_WRITING_NEW_PDF = 6
    STATUS_NO_ACCEPTABLE_WEBS_FOUND = 7
